/**
 * NativeWind TypeScript Environment Declaration
 *
 * This reference directive adds the `className` prop to all React Native
 * core components (View, Text, Pressable, etc.) so TypeScript doesn't
 * complain when you use Tailwind classes.
 *
 * This file is auto-generated by NativeWind's Metro plugin but can also
 * be manually created. Do not delete it.
 */
/// <reference types="nativewind/types" />
