export const PRESET_ACTIVITIES = [
  "Take out the trash",
  "Do the dishes",
  "Vacuum the floor",
  "Clean bathroom",
  "Make the bed",
  "Do laundry",
  "Walk the dog",
  "Feed the pet",
  "Water the plants",
  "Mow the lawn",
  "Sweep the floor",
  "Wipe down counters",
  "Organize closet",
  "Tidy bedroom",
  "Set the table",
  "Unload dishwasher",
  "Fold laundry",
  "Take out recycling",
  "Dust furniture",
  "Read for 30 minutes",
];
